language: node_js

node_js:
  - '10'

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test

before_deploy:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: 'build'
  on:
    branch: master
